// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW57mXUElJTwCUk6Z6A3UnbLT_NAyO_1g',
    appId: '1:351040484888:web:3ecde95eaf4cae94ec356d',
    messagingSenderId: '351040484888',
    projectId: 'festidriver',
    authDomain: 'festidriver.firebaseapp.com',
    databaseURL: 'https://festidriver-default-rtdb.firebaseio.com',
    storageBucket: 'festidriver.firebasestorage.app',
    measurementId: 'G-JW85W8JF7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXP8acLS5UEvq0PZJDLtFBTsaBq13TxBQ',
    appId: '1:351040484888:android:b06e489bbfb6ec48ec356d',
    messagingSenderId: '351040484888',
    projectId: 'festidriver',
    databaseURL: 'https://festidriver-default-rtdb.firebaseio.com',
    storageBucket: 'festidriver.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzX2V4DPH2eLoUljwcOyA-ZXL_WhEGpmU',
    appId: '1:351040484888:ios:2de20958741c50e5ec356d',
    messagingSenderId: '351040484888',
    projectId: 'festidriver',
    databaseURL: 'https://festidriver-default-rtdb.firebaseio.com',
    storageBucket: 'festidriver.firebasestorage.app',
    iosClientId: '351040484888-p9htpg4a03gu8b0tj2q27ldc6g8pptrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.festidriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzX2V4DPH2eLoUljwcOyA-ZXL_WhEGpmU',
    appId: '1:351040484888:ios:2de20958741c50e5ec356d',
    messagingSenderId: '351040484888',
    projectId: 'festidriver',
    databaseURL: 'https://festidriver-default-rtdb.firebaseio.com',
    storageBucket: 'festidriver.firebasestorage.app',
    iosClientId: '351040484888-p9htpg4a03gu8b0tj2q27ldc6g8pptrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.festidriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW57mXUElJTwCUk6Z6A3UnbLT_NAyO_1g',
    appId: '1:351040484888:web:9df4e3f9bb215e6dec356d',
    messagingSenderId: '351040484888',
    projectId: 'festidriver',
    authDomain: 'festidriver.firebaseapp.com',
    databaseURL: 'https://festidriver-default-rtdb.firebaseio.com',
    storageBucket: 'festidriver.firebasestorage.app',
    measurementId: 'G-CYC4RR5FP4',
  );
}
